### ISSUE TITLE
Reflective glass type mapped to low-e

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#102]
It probably shouldn't be. What should it be mapped to?

This came up in #100. 

@lirainer

**Comment by lirainer** [comment]
HES does not have glazing assembly codes to handle `reflective` so it would need to be mapped to either `tinted` or `low-e` or `clear`, all of which are incorrect. Biggest issue is optics: an HPXML input with `reflective glass` now shows `low-e` on the label. Given that `reflective` is extremely rare in residential construction I recommend we leave the mapping as is, make sure the issue is documented, and eventually fix it by mapping to Energy Plus glazing characteristics directly, rather than using the HES glazing assembly codes.

**Comment by nmerket** [comment]
It is generally documented [here](https://hescore-hpxml.readthedocs.io/en/latest/translation/zone_window.html#window-properties). (I should probably review to make sure it's still correct.) I'm fine with leaving it as is for now.
