### ISSUE TITLE
Skylight is always assigned to first roof

### ISSUE THREAD

**Issue by shorowit** [NREL/hescore-hpxml#135]
Can/should the skylight be able to be assigned to the second roof? See original discussion [here](https://github.com/NREL/OpenStudio-HEScore/pull/237).

**Comment by lirainer** [comment]
I've searched my communications and couldn't find anything related to this decision. If I could find when the skylight change was implemented I might be able to find more details, but using blame on base.py I can't look back farther than the v2/3 refactoring - e0c4bc95b1e1fb7d5c32f949ec80506cca5ff6c7. @nmerket or @yzhou601  is there a way to find when [the skylight assignment](https://github.com/NREL/hescore-hpxml/blob/master/hescorehpxml/base.py#L761) was implemented?

**Comment by shorowit** [comment]
Looks to have been [this commit ("translating up to two attics/roofs")](https://github.com/NREL/hescore-hpxml/pull/30/commits/db93c4392abf9dfcea3909d95311a3510f563e17) as part of [this PR](https://github.com/NREL/hescore-hpxml/pull/30).

**Comment by lirainer** [comment]
Thanks @shorowit. I have searched my email for that time period and could not find any discussion about skylights in hpxml2hescore so we probably made the decision on a call. I expect it was in order to keep things as similar to the GUI as possible because at that time most runs were done with the GUI. I believe that most are done with either the API or HPXML now so I would recommend putting the skylight on the roof it is attached to. Glenn doesn't appear to be on this repo so I will send him an email as he should make the final call.

**Comment by shorowit** [comment]
This is a public repo so everyone can access it. Adding @gdickey627 to the conversation...

**Comment by gdickey627** [comment]
Go ahead and move it so the inputs align with the appropriate roof.  Thanks

**Comment by shorowit** [comment]
FYI, I found the reason it's assigned to the first roof: https://github.com/NREL/hescore-hpxml/issues/21#issuecomment-75866952
