### ISSUE TITLE
Better error message for impossible townhouse walls

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#211]
**Describe the bug**

If a town house has a front door on the opposite side of the house from the attached wall, there is no `about.town_house_walls` that permits that configuration. It only allows `back_right_front` and `back_front_left` Those are the descriptors of the exposed, not attached, walls. The translator when trying to figure out how to arrange walls and windows and get it to fit the constraints of the API gets confused and gives a not helpful error message.

**Error Message**

```
HPXML to JSON translation failed with errors: The house has windows on shared walls.
```

**To Reproduce**
Please provide an HPXML file that hits the error with any personally identifiable information removed.

[OptiMiserDirect-2022-07-31-1116-hes-hpxml-scrubbed.xml.txt](https://github.com/NREL/hescore-hpxml/files/9237868/OptiMiserDirect-2022-07-31-1116-hes-hpxml-scrubbed.xml.txt)

**Expected behavior**

Until we fix the API to allow more town house configurations, this should return an error message that is more descriptive of what's actually going on.

**Environment (please complete the following information):**
 - OS: Mac
 - Python Version: 3.9

**Comment by lirainer** [comment]
A couple of thoughts on this:
1. I have never liked the `town_house_walls` enumerations. They leaked through from our Multimaily API and I think it would be better to use something more like what HPXML has. Maybe we could do this as part of the MF/Manufactured changes?
2. For now we could very easily add a `front_right_left` enumeration to handle this use case since it is already in `lu_zone_orientation`. But would also have to add something to the workflow to handle it.

**Comment by nmerket** [comment]
Yes, we would. This is more of a band-aid until we can properly do this better for multifamily. I'd like to keep this as simple as possible, if we do anything at all. Part of me wants to just accept this as a known bug until we push that other change out.
