### ISSUE TITLE
Window error on townhome with one shared wall

### ISSUE THREAD

**Issue by brandongallagher** [NREL/hescore-hpxml#53]
I am sending a home with one shared wall.  I am getting the error below.  This is on the PNNL sandbox server.

```
Building #98001 validation failed. The following fields have errors: //zone_wall[side[text()='right']]/zone_window/window_area: Missing //zone_wall[side[text()='right']]/zone_window/window_method: Missing 
```

The HPXML I'm sending has four walls, one for each diretion.  The shared one has:
`<ExteriorAdjacentTo>other housing unit</ExteriorAdjacentTo>`

I only included three windows, one for each of the non-shared walls.

I attached the HPXML I'm sending along with the HES interpretation of that.

I think this may be related to https://github.com/NREL/hescore-hpxml/issues/52

[98001.zip](https://github.com/NREL/hescore-hpxml/files/110056/98001.zip)

**Comment by lirainer** [comment]
@brandongallagher @nmerket This is not an hpxml conversion problem but is due to an HEScore error. It is [101 - Windows required on common walls for building.shape=town_house](http://hes-documentation.lbl.gov/home-energy-scoring-tool/known-issues). I will let you know as soon as it has been fixed and available for testing. In the meantime this building can be run if you set window_construction_same to true (since the two with area are both type dpeaw) and run calculate_base_building() with validate_inputs=false. But I'm not sure how to do that in hpxml.

**Comment by nmerket** [comment]
To do it in HPXML you'd have to submit the HXPML file and then change the HEScore inputs through the API. There is no way to set the window construction to all be the same in HPXML. Sorry for the hassle.

**Comment by nmerket** [comment]
@lirainer Do we have a resolution to this on your end?

**Comment by lirainer** [comment]
@nmerket @brandongallagher This was an HEScore validation issue ([#101](https://gitlab.hescloud.net/hes-api-code/hes-api-ci/issues/101)) and was resolved and pushed to production in April.
